name: remote-wait-list-manager

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - remote-wait-list-manager-network
    ports:
      - 5000:5000
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - remote-wait-list-manager-network
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - api

networks:
  remote-wait-list-manager-network:
    driver: bridge
